include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "scratch/**"
    - "bin/**"
  errors:
    deprecated_member_use: ignore
    unnecessary_import: ignore

linter:
  rules:
    avoid_print: true
