// File generated by Manual Integration and following Production Readiness Audit
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Placeholder for Web - Not configured yet
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfM4csK8u13t80oHOT8I9aMKGx-pe4EM',
    appId: '1:860837572098:android:5a9d7594b32d94b1e5c11b',
    messagingSenderId: '860837572098',
    projectId: 'vsp-app-103b1',
    storageBucket: 'vsp-app-103b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8fA59czNAHzQzrZx6fnaiiJWsXJXWOM',
    appId: '1:860837572098:ios:066a97a8bcad9a1ee5c11b',
    messagingSenderId: '860837572098',
    projectId: 'vsp-app-103b1',
    storageBucket: 'vsp-app-103b1.firebasestorage.app',
    iosBundleId: 'com.example.vspApplication',
  );
}
