CREATE OR REPLACE FUNCTION public.get_owner_ai_operational_insights(p_owner_id uuid,p_period text DEFAULT '30d')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
declare v_caller_id uuid:=auth.uid(); v_caller_role text; v_now timestamptz:=now(); v_from timestamptz; v_to timestamptz:=v_now;
v_period text:=lower(coalesce(trim(p_period),'30d')); v_period_days numeric:=30; v_total_bookings int:=0; v_completed_bookings int:=0; v_confirmed_bookings int:=0; v_cancelled_bookings int:=0;
v_gross_booking_value numeric:=0; v_realized_revenue numeric:=0; v_booked_hours numeric:=0; v_available_hours numeric:=0; v_utilization_pct numeric:=0; v_cancellation_rate_pct numeric:=0; v_avg_booking_value numeric:=0; v_stadium_count int:=0;
v_cash_debt numeric:=0; v_debt_limit numeric:=0; v_debt_blocked boolean:=false; v_alerts jsonb:='[]'::jsonb;
begin
if v_caller_id is null and current_user not in ('postgres','service_role') then return jsonb_build_object('success',false,'error','Authentication required'); end if;
if v_caller_id is not null then select role into v_caller_role from public.users where id=v_caller_id; if v_caller_id<>p_owner_id and coalesce(v_caller_role,'') not in ('admin','co_founder','cofounder','super_admin') and current_user not in ('postgres','service_role') then return jsonb_build_object('success',false,'error','Unauthorized access to owner insights'); end if; end if;
select coalesce(accumulated_cash_debt,0),coalesce(debt_limit,0),coalesce(is_debt_blocked,false) into v_cash_debt,v_debt_limit,v_debt_blocked from public.users where id=p_owner_id and role='owner';
v_from:=case v_period when '7d' then v_now-interval '7 days' when '90d' then v_now-interval '90 days' when 'all' then '1970-01-01 00:00:00+00'::timestamptz else v_now-interval '30 days' end; v_period_days:=greatest(1,extract(epoch from(v_to-v_from))/86400.0);
select count(*)::int,count(*) filter(where status='completed')::int,count(*) filter(where status='confirmed')::int,count(*) filter(where status='cancelled')::int,coalesce(sum(total_price),0) into v_total_bookings,v_completed_bookings,v_confirmed_bookings,v_cancelled_bookings,v_gross_booking_value from public.bookings where owner_id=p_owner_id and created_at>=v_from and created_at<=v_to;
select coalesce(sum(total_price),0) into v_realized_revenue from public.bookings where owner_id=p_owner_id and created_at>=v_from and created_at<=v_to and status='completed' and payment_status='paid';
select coalesce(sum(greatest(0,extract(epoch from(least(end_time,v_to)-greatest(start_time,v_from)))/3600.0)),0) into v_booked_hours from public.bookings where owner_id=p_owner_id and status<>'cancelled' and end_time>v_from and start_time<v_to;
select count(*)::int into v_stadium_count from public.stadiums where owner_id=p_owner_id and coalesce(is_deleted_by_owner,false)=false;
select coalesce(sum(((case when s.closing_time>s.opening_time then extract(epoch from(s.closing_time-s.opening_time))/3600.0 else extract(epoch from(s.closing_time-s.opening_time))/3600.0+24 end)-case when coalesce(s.is_split_shift,false) and s.break_start_time is not null and s.break_end_time is not null then case when s.break_end_time>=s.break_start_time then extract(epoch from(s.break_end_time-s.break_start_time))/3600.0 else extract(epoch from(s.break_end_time-s.break_start_time))/3600.0+24 end else 0 end)*v_period_days),0) into v_available_hours from public.stadiums s where s.owner_id=p_owner_id and coalesce(s.is_deleted_by_owner,false)=false and s.opening_time is not null and s.closing_time is not null;
if v_available_hours>0 then v_utilization_pct:=round(v_booked_hours/v_available_hours*100,2); end if;
if v_total_bookings>0 then v_cancellation_rate_pct:=round(v_cancelled_bookings::numeric/v_total_bookings*100,2); v_avg_booking_value:=round(v_gross_booking_value/v_total_bookings,2); end if;
if v_cash_debt>0 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('code','CASH_DEBT','severity',case when v_debt_blocked or (v_debt_limit>0 and v_cash_debt>=v_debt_limit) then 'critical' else 'warning' end,'metric','accumulated_cash_debt','value',round(v_cash_debt,2),'debt_limit',round(v_debt_limit,2))); end if;
if v_total_bookings=0 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('code','NO_BOOKINGS_IN_PERIOD','severity','info','metric','total_bookings','value',0,'message_ar','لا توجد حجوزات مسجلة في الفترة المحددة.','evidence',jsonb_build_object('period',v_period))); else
if v_utilization_pct<25 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('code','LOW_UTILIZATION','severity','warning','metric','utilization_pct','value',v_utilization_pct,'threshold',25)); elsif v_utilization_pct>=70 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('code','HIGH_UTILIZATION','severity','info','metric','utilization_pct','value',v_utilization_pct,'threshold',70)); end if;
if v_cancellation_rate_pct>=15 then v_alerts:=v_alerts||jsonb_build_array(jsonb_build_object('code','HIGH_CANCELLATION_RATE','severity','warning','metric','cancellation_rate_pct','value',v_cancellation_rate_pct,'threshold',15)); end if; end if;
return jsonb_build_object('success',true,'owner_id',p_owner_id,'period',v_period,'period_start',v_from,'period_end',v_to,'stadium_count',v_stadium_count,'total_bookings',v_total_bookings,'completed_bookings',v_completed_bookings,'confirmed_bookings',v_confirmed_bookings,'cancelled_bookings',v_cancelled_bookings,'gross_booking_value',round(v_gross_booking_value,2),'realized_revenue',round(v_realized_revenue,2),'booked_hours',round(v_booked_hours,2),'available_hours_estimate',round(v_available_hours,2),'utilization_pct',v_utilization_pct,'cancellation_rate_pct',v_cancellation_rate_pct,'average_booking_value',v_avg_booking_value,'accumulated_cash_debt',round(v_cash_debt,2),'debt_limit',round(v_debt_limit,2),'is_debt_blocked',v_debt_blocked,'alerts',v_alerts);
end; $$;